// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASjLmgiwzqO-hF29ZFw-PtfcVvCW023Hs',
    appId: '1:870491136725:web:fb8748f00d3c700ee9785c',
    messagingSenderId: '870491136725',
    projectId: 'aob-finance',
    authDomain: 'aob-finance.firebaseapp.com',
    storageBucket: 'aob-finance.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuGU5Ms5IARqXMSaDgz5heyH745jvQrX8',
    appId: '1:870491136725:android:31c859d6c7de9359e9785c',
    messagingSenderId: '870491136725',
    projectId: 'aob-finance',
    storageBucket: 'aob-finance.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASjLmgiwzqO-hF29ZFw-PtfcVvCW023Hs',
    appId: '1:870491136725:web:f13a249f531b4ad7e9785c',
    messagingSenderId: '870491136725',
    projectId: 'aob-finance',
    authDomain: 'aob-finance.firebaseapp.com',
    storageBucket: 'aob-finance.firebasestorage.app',
  );
}
