// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwhKqt957EAXnOccJpkb8UpoNADnP_tHg',
    appId: '1:221687267179:web:f647c5a77f24b932e9d62e',
    messagingSenderId: '221687267179',
    projectId: 'aidhub-e720d',
    authDomain: 'aidhub-e720d.firebaseapp.com',
    storageBucket: 'aidhub-e720d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBuGCfOR0xDiIsX_APOA_F8yAt-CKusaY',
    appId: '1:221687267179:android:fa0499b975c374f6e9d62e',
    messagingSenderId: '221687267179',
    projectId: 'aidhub-e720d',
    storageBucket: 'aidhub-e720d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwhKqt957EAXnOccJpkb8UpoNADnP_tHg',
    appId: '1:221687267179:web:cd0f386864b43e74e9d62e',
    messagingSenderId: '221687267179',
    projectId: 'aidhub-e720d',
    authDomain: 'aidhub-e720d.firebaseapp.com',
    storageBucket: 'aidhub-e720d.firebasestorage.app',
  );
}
